-- Database Schema Export: 2026-01-27 22:47:08.736423
-- Auto-generated by AI Assistant

-- Table: item
CREATE TABLE IF NOT EXISTS item (
    item_id character varying(20.0) NOT NULL DEFAULT nan,
    item_type USER-DEFINED(nan) DEFAULT nan,
    item_quantity_type USER-DEFINED(nan) DEFAULT nan,
    activity_status USER-DEFINED(nan) DEFAULT nan,
    demand_avg numeric(nan) DEFAULT nan,
    demand_deviation numeric(nan) DEFAULT nan,
    min_buffer numeric(nan) DEFAULT 0
);

-- Table: supplier_item
CREATE TABLE IF NOT EXISTS supplier_item (
    item_id character varying(20.0) NOT NULL DEFAULT nan,
    supplier_id character varying(20.0) NOT NULL DEFAULT nan,
    calculated_leadtime_avg numeric(nan) DEFAULT nan,
    calculated_leadtime_deviation numeric(nan) DEFAULT nan,
    given_leadtime numeric(nan) DEFAULT nan,
    given_leadtime_deviation numeric(nan) DEFAULT nan,
    lot_size numeric(nan) DEFAULT 0,
    min_size numeric(nan) DEFAULT 0,
    max_size numeric(nan) DEFAULT 0,
    calculated boolean(nan) DEFAULT nan,
    activity_status USER-DEFINED(nan) DEFAULT nan
);

-- Table: stock_movement
CREATE TABLE IF NOT EXISTS stock_movement (
    id integer(nan) NOT NULL DEFAULT nextval('stock_movement_id_seq'::regclass),
    item_id character varying(20.0) DEFAULT nan,
    amount numeric(nan) DEFAULT nan,
    purpose USER-DEFINED(nan) DEFAULT nan,
    date date(nan) DEFAULT nan
);

-- Table: start_inventories
CREATE TABLE IF NOT EXISTS start_inventories (
    item_id character varying(20.0) NOT NULL,
    date date(nan) NOT NULL DEFAULT nan,
    amount numeric(nan) DEFAULT nan
);

-- Table: sales_out_history
CREATE TABLE IF NOT EXISTS sales_out_history (
    id integer(nan) NOT NULL DEFAULT nextval('sales_out_history_id_seq'::regclass),
    item_id character varying(20.0) DEFAULT nan,
    amount numeric(nan) DEFAULT nan,
    date date(nan) DEFAULT nan
);

-- Table: prophet_table_history
CREATE TABLE IF NOT EXISTS prophet_table_history (
    item_id character varying(20.0) NOT NULL,
    date date(nan) NOT NULL DEFAULT nan,
    amount numeric(nan) DEFAULT nan
);

-- Table: prophet_table_temporary
CREATE TABLE IF NOT EXISTS prophet_table_temporary (
    item_id character varying(20.0) NOT NULL,
    date date(nan) NOT NULL DEFAULT nan,
    amount numeric(nan) DEFAULT nan
);

-- Table: purchase
CREATE TABLE IF NOT EXISTS purchase (
    id integer(nan) NOT NULL DEFAULT nextval('purchase_id_seq'::regclass),
    item_id character varying(20.0) DEFAULT nan,
    supplier_id character varying(20.0) DEFAULT nan,
    amount numeric(nan) DEFAULT nan,
    purchase_date date(nan) DEFAULT nan,
    expected_coming_date date(nan) DEFAULT nan,
    actual_coming_date date(nan) DEFAULT nan,
    delay_day numeric(nan) DEFAULT nan,
    status character varying(nan) DEFAULT nan,
    purpose USER-DEFINED(nan) DEFAULT nan
);

-- Table: active_inventory
CREATE TABLE IF NOT EXISTS active_inventory (
    item_id character varying(20.0) NOT NULL DEFAULT nan,
    current_stock numeric(nan) DEFAULT 0
);

-- Table: customer_orders
CREATE TABLE IF NOT EXISTS customer_orders (
    id integer(nan) NOT NULL DEFAULT nextval('customer_orders_id_seq'::regclass),
    customer_name character varying(100.0) DEFAULT nan,
    item_id character varying(20.0) DEFAULT nan,
    amount numeric(nan) DEFAULT nan,
    order_date date(nan) DEFAULT nan,
    expected_delivery_date date(nan) DEFAULT nan,
    delivery_date date(nan) DEFAULT nan,
    production_time_days integer(nan) DEFAULT nan,
    status USER-DEFINED(nan) DEFAULT 'Bekleniyor'::customer_order_status_enum
);

-- Table: ss_kings_formula
CREATE TABLE IF NOT EXISTS ss_kings_formula (
    item_id character varying(20.0) NOT NULL DEFAULT nan,
    supplier_id character varying(20.0) NOT NULL DEFAULT nan,
    demand_avg numeric(nan) DEFAULT nan,
    leadtime_avg numeric(nan) DEFAULT nan,
    demand_deviation numeric(nan) DEFAULT nan,
    leadtime_deviation numeric(nan) DEFAULT nan,
    z_score numeric(nan) DEFAULT 1.64,
    result_king numeric(nan) DEFAULT nan,
    activity_status USER-DEFINED(nan) DEFAULT nan
);

-- Table: ss_ai_history
CREATE TABLE IF NOT EXISTS ss_ai_history (
    item_id character varying(20.0) NOT NULL,
    date date(nan) NOT NULL DEFAULT nan,
    amount numeric(nan) DEFAULT nan
);

-- Table: ss_ai_temporary
CREATE TABLE IF NOT EXISTS ss_ai_temporary (
    item_id character varying(20.0) NOT NULL,
    date date(nan) NOT NULL DEFAULT nan,
    amount numeric(nan) DEFAULT nan
);

-- Table: final_safety_stock
CREATE TABLE IF NOT EXISTS final_safety_stock (
    item_id character varying(20.0) NOT NULL DEFAULT nan,
    safety_stock numeric(nan) DEFAULT 0,
    item_quantity_type USER-DEFINED(nan) DEFAULT nan,
    date date(nan) NOT NULL DEFAULT nan
);

-- Table: calculated_full_ss_ai_temp
CREATE TABLE IF NOT EXISTS calculated_full_ss_ai_temp (
    item_id character varying(20.0) NOT NULL,
    date date(nan) NOT NULL DEFAULT nan,
    amount numeric(nan) DEFAULT nan,
    status USER-DEFINED(nan) NOT NULL DEFAULT nan,
    item_type USER-DEFINED(nan) DEFAULT nan,
    item_quantity_type USER-DEFINED(nan) DEFAULT nan
);

-- Table: bom
CREATE TABLE IF NOT EXISTS bom (
    parent_id character varying(20.0) NOT NULL,
    child_id character varying(20.0) NOT NULL,
    amount numeric(nan) DEFAULT nan,
    activity_status USER-DEFINED(nan) DEFAULT nan
);

-- Table: sip_harita_active_inventory
CREATE TABLE IF NOT EXISTS sip_harita_active_inventory (
    item_id character varying(20.0) NOT NULL DEFAULT nan,
    current_stock numeric(nan) DEFAULT 0
);

-- Table: order_material_consumption
CREATE TABLE IF NOT EXISTS order_material_consumption (
    id SERIAL PRIMARY KEY,
    order_id INTEGER REFERENCES customer_orders(id) ON DELETE CASCADE,
    item_id VARCHAR(20) REFERENCES item(item_id) ON DELETE CASCADE,
    amount NUMERIC DEFAULT 0,
    date DATE DEFAULT CURRENT_DATE,
    UNIQUE(order_id, item_id)
);

