from backend.database.db_helper import run_query, run_command
from backend.modules.simulation.order_map.demand_processor import process_demand
from backend.modules.simulation.order_map.order_effect_tracker import set_current_order_id, clear_current_order_id
from backend.modules.simulation.order_map.sim_supplier_checker import get_missing_suppliers
from backend.logger import get_logger

logger = get_logger(__name__)


def rebuild_simulation_from_scratch():
    """
    Sistemi sıfırlar (planned_inventory = active_inventory) ve bekleyen
    tüm siparişleri baştan sona simüle eder. Ağırdır ancak %100 doğruluk sağlar.
    """
    logger.info("Rebuilding entire simulation from scratch...")
    
    # 1. Reset Planned Inventory from Active Inventory
    run_command("TRUNCATE TABLE planned_inventory")
    run_command("""
    INSERT INTO planned_inventory (item_id, planned_stock)
    SELECT item_id, current_stock FROM active_inventory
    """)
    
    # 2. Reset Purchases that were generated by Simulation (Bekleniyor)
    run_command("DELETE FROM purchase WHERE status = 'Bekleniyor'")
    
    # 3. Clear all Effect tracking logs
    run_command("TRUNCATE TABLE order_simulation_effects")
    
    # 4. Get all pending Customer Orders sorted by due date
    orders_df = run_query("SELECT * FROM customer_orders WHERE status IN ('Bekleniyor', 'Üretimde') ORDER BY expected_delivery_date ASC, id ASC")
    
    if orders_df.empty:
        logger.info("No pending orders to simulate.")
        return []
        
    warnings = []
    
    # 5. Process each order
    for _, order in orders_df.iterrows():
        try:
             set_current_order_id(order['id'])
             due_date = order['expected_delivery_date'] or order['order_date']
             prod_time = int(order['production_time_days'] or 0)
             
             process_demand(order['item_id'], float(order['amount']), due_date, prod_time)
        except Exception as e:
             logger.error(f"Error simulating order {order['id']}: {e}")
             warnings.append({"order_id": order['id'], "error": str(e)})
        finally:
             clear_current_order_id()
             
    # 6. Check for missing suppliers after all simulation
    missing = get_missing_suppliers()
    if missing:
         for item in missing:
             warnings.append({"item_id": item, "type": "missing_supplier"})
             
    logger.info("Simulation rebuild complete.")
    return warnings

def get_simulation_results():
    """
    Çalıştırılmış olan simülasyonun sonuçlarını döner:
    - Bekleyen Siparişler
    - Eksilen Stok Durumu (Planned Inventory, negative items flag)
    - Satın Alma İhtiyaçları (Bekleniyor statülü Purchase'lar)
    """
    
    # 1. Bekleyen / Sorunlu Stoklar
    stock_df = run_query("""
    SELECT p.item_id, p.planned_stock, i.item_type, i.item_quantity_type
    FROM planned_inventory p
    JOIN item i ON p.item_id = i.item_id
    WHERE p.planned_stock < 0
    ORDER BY p.planned_stock ASC
    """)
    
    # 2. Satınalma İhtiyaçları
    purchases_df = run_query("""
    SELECT p.item_id, p.amount, p.expected_coming_date, s.supplier_id
    FROM purchase p
    LEFT JOIN supplier_item s ON p.item_id = s.item_id AND p.supplier_id = s.supplier_id
    WHERE p.status = 'Bekleniyor'
    ORDER BY p.expected_coming_date ASC
    """)
    
    # Replace NaN/NaT with explicit None/empty string for JSON serialization
    stock_records = stock_df.fillna("").to_dict(orient="records") if not stock_df.empty else []
    
    purchases_records = []
    if not purchases_df.empty:
        # Convert datetime to string
        purchases_df['expected_coming_date'] = purchases_df['expected_coming_date'].astype(str)
        purchases_records = purchases_df.fillna("").to_dict(orient="records")
    
    return {
        "stock_warnings": stock_records,
        "purchase_needs": purchases_records
    }
